const user = require("./controller/user")
// user.addUser("marwa", 37, "marwa@gmail.com")
// user.readAll()
// user.singleUser("99hn349cl4b2f9e")
user.editUser("99hn349cl4b2nf9e", {name:"a", age:"c"})
